### ISSUE TITLE
Don't rely on reduce being fold-left

### ISSUE THREAD

**Issue by stevengj** [pao/Monads.jl#3]
As you mentioned today, the code

```
mdo_desugar(exprIn) = reduce(mdo_desugar_helper, :(), reverse(exprIn.args))
```

assumes that the associativity of `reduce` is fold-left, which is true of the current implementation but is undocumented, and may change (JuliaLang/julia#4046).

In any case,

```
function mdo_desugar(exprIn)
    r = :()
    for i = length(exprIn.args):-1:1
        r = mdo_desugar_helper(exprIn.args[i], r)
    end
    r
end
```

has the additional virtue of being faster (since it avoids the call to `reverse` and the allocation of a new array), not that it probably matters to you.

**Comment by jfarid27** [comment]
Closing since it's old

**Comment by stevengj** [comment]
The bug in `mdo_desugar` (relying on associativity of `reverse`) is still there in the current code.  It should just call `foldl`.

**Comment by ulysses4ever** [comment]
@stevengj would you create a PR?

**Comment by jfarid27** [comment]
@stevengj also, can you check out
